# Change these first
owner: AlexDevUwU # Your GitHub username
repo: quackhostuptimecheckerweb # Your GitHub repository name

# Add your sites here
sites:
  - name: QuackHost Client
    url: https://client.quackhost.uk/
  - name: QuackHost GameCP
    url: https://gamecp.quackhost.uk/
  - name: FIFR3 CPU API
    url: http://95.217.226.152:26002/cpu
  - name: FIFR3 DISK API
    url: http://95.217.226.152:26002/disk
  - name: FIFR3 RAM API
    url: http://95.217.226.152:26002/ram

status-website:
  baseUrl: /quackhostuptimecheckerweb # where "repo" is your repository name
  logoUrl: https://client.quackhost.uk/assets/img/logo.png
  name: QuackHost Custom Uptime Checker
  introTitle: "**QuackHost Uptime Checker** es un uptime checker creado únicamente con herramientas de GitHub."
  introMessage: "Creado por AlexDevUwU"
  navbar:
    - title: Estado
      href: /
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
